### ISSUE TITLE
Vanity address tool

### ISSUE THREAD

**Issue by gak** [feeless/feeless#23]
Generate a phrase, seed or private key to product a Nano address that matches some sort of criteria.

For example, I might want to have an address that starts with `nano_1gakman`.

Could use ANSI to show the status on the same line, or just print a new line for each status update. The status updates should be put into standard error, so that standard output should only contain the result, e.g. a phrase or a private key.

```
> feeless vanity phrase 1gak
Generating random phrases to look for 1gak
5,000 phrases generated
10,000 phrases generated
Found!
logic unlock retreat water shell outdoor dress spatial wood proud push salute produce pipe mammal tail powder print flower fashi
on stove agent dwarf organ
```

An option might allow a regular expression, and maybe just `--ending-with`.

I think the positional argument should just be an optional "starting with", but also have the option to be consistent.

```
--starting-with [text] also default positional argument
--ending-with [text]
--re [text]
```

This would also need to make sure the text entered must match the possible characters in a Nano address.

Multiple CPU threads would be ideal, along with letting the user choose how many threads or use all CPU threads by default.

- [x] `feeless vanity` command
- [x] Default positional argument for `--starting-with`
- [x] `--ending-with`
- [x] `--re`
- [x] stderr status/progress
- [x] Final result for
  - [x] Phrase
    - [x] Must support same arguments as `feeless phrase new`, i.e. language and words
  - [x] Seed
  - [x] Private key
- [x] `--threads`
- [x] Default threads based on CPU logical processors

**Comment by Fiono11** [comment]
This tool can be useful: https://github.com/PlasmaPower/nano-vanity

**Comment by gak** [comment]
> This tool can be useful: https://github.com/PlasmaPower/nano-vanity

Thanks, I've been eyeing it for a while :) The CPU generation is probably faster, but I wanted to use the feeless types for it.

**Comment by gak** [comment]
Turns out CPU generation is in the same ballpark without doing any performance tweaks.
